### ISSUE TITLE
Celo: <Issue Title>private key 

### ISSUE THREAD

**Issue by Henrydiarua9** [celo-org/blockscout#1108]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 004cf3faf83aeab893c383de028cbf3c49903cfa

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/blockscout/pull/1107
- [x] https://github.com/celo-org/blockscout/issues/1109
- [ ] https://github.com/celo-org/blockscout/issues/1104
- [ ] https://github.com/celo-org/blockscout/issues/1106
- [ ] https://github.com/celo-org/blockscout/issues/1102
- [ ] https://github.com/celo-org/blockscout/issues/1105
```
