### ISSUE TITLE
Opération  stay safe 

### ISSUE THREAD

**Issue by Covitluat77** [celo-org/blockscout#1131]
Dévelope .gov for none entrie for other countries in tell we have understanding *Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):

* Node JS version (`node -v`): Python for border parole fund 
* 
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### behavioral data to not to appe t passports for countries we didn't accept because this change 

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

```[tasklist]
### Tasks
- [x] Behavioral blocks for safety concern
- [ ] https://github.com/celo-org/blockscout/issues/1130
- [ ] https://github.com/celo-org/blockscout/issues/1127
```
